//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendeAgroWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago_Concepto
    {
        public int id { get; set; }
        public int idPago { get; set; }
        public Nullable<int> idPlazo { get; set; }
        public Nullable<int> idBeneficio { get; set; }
        public bool tipo { get; set; }
    
        public virtual Beneficio Beneficio { get; set; }
        public virtual Pago Pago { get; set; }
        public virtual Plazo Plazo { get; set; }
    }
}
