//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendeAgroWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anuncio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anuncio()
        {
            this.Anuncio_Beneficio = new HashSet<Anuncio_Beneficio>();
            this.Fotos_Anuncio = new HashSet<Fotos_Anuncio>();
            this.Videos_Anuncio = new HashSet<Videos_Anuncio>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> precio { get; set; }
        public bool activo { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idSubcategoria { get; set; }
        public Nullable<int> idCiudad { get; set; }
        public Nullable<int> clicks { get; set; }
        public Nullable<int> vistas { get; set; }
        public int estado { get; set; }
        public string razonRechazo { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<int> idPaquete { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Paquete Paquete { get; set; }
        public virtual Subcategoria Subcategoria { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anuncio_Beneficio> Anuncio_Beneficio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fotos_Anuncio> Fotos_Anuncio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Videos_Anuncio> Videos_Anuncio { get; set; }
    }
}
