//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendeAgroWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago_Concepto
    {
        public int id { get; set; }
        public int idPago { get; set; }
        public bool tipo { get; set; }
        public string descripcionBeneficio { get; set; }
        public Nullable<double> precioBeneficio { get; set; }
        public Nullable<int> tipoBeneficio { get; set; }
        public string nombrePaquete { get; set; }
        public int mesesPaquete { get; set; }
        public double precioPaquete { get; set; }
        public string descripcionPaquete { get; set; }
    
        public virtual Pago Pago { get; set; }
    }
}
