//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendeAgroWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pago()
        {
            this.Pago_Concepto = new HashSet<Pago_Concepto>();
        }
    
        public int id { get; set; }
        public int idUsuario { get; set; }
        public int tipoTarjeta { get; set; }
        public string digitosTarjeta { get; set; }
        public double total { get; set; }
        public System.DateTime fecha { get; set; }
        public int tipo { get; set; }
        public string Referencia { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago_Concepto> Pago_Concepto { get; set; }
    }
}
