//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendeAgroWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paquete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paquete()
        {
            this.Anuncios = new HashSet<Anuncio>();
            this.Conekta_Paquete = new HashSet<Conekta_Paquete>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public int meses { get; set; }
        public double precio { get; set; }
        public string descripcion { get; set; }
        public bool paqueteBase { get; set; }
        public System.DateTime fechaModificacion { get; set; }
        public bool activo { get; set; }
        public double porcentajeAhorro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anuncio> Anuncios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conekta_Paquete> Conekta_Paquete { get; set; }
    }
}
